### PR TITLE
#5: Step 3 (closes #5)

### LINKED ISSUE #5: Step 3
## requirements
Use a `Move` model instead of Strings.

## specs
- convert the user input to a valid Move data type
- use ADT (Algebraic Data Type, i.e. sealed case objects in Scala) encoding for enum (see https://underscore.io/blog/posts/2014/09/03/enumerations.html)
- use an Option to signal the parsing can fail
- refactor the implementation to work with the `Move` data type

## misc

- The enum encoding uses an ADT (Algebraic Data Type), which in scala is a `sealed trait` extended by `case object` (more on the subject here: https://underscore.io/blog/posts/2014/09/03/enumerations.html)
- we decided to use `Option` to represent the fact that the parsing of a move can fail. This forces us to handle the case in which the user input is invalid. We use pattern match to see whether we got a valid move or not and then move on.
  - we could’ve used more sophisticated data types for the purposes of validating stuff
  - if you’re super curious see for instance `Validated`, a data type that allows composing multiple validations on the input, while preserving the failure reasons for each validation.
- computer move is now chosen amongst a list of valid moves
- the business logic (inside the pattern match) is now much clearer to read and debug

### Solution
https://github.com/buildo/rps/compare/step-2...step-3

### PR DESCRIPTION
**Pull request by raasoft**
Closes #5

### tests performed

kapture 2018-07-11 at 16 04 01

### CODE REVIEW

File: src/main/scala/rps/RPSMoves.scala [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+object RPSMoves {
+
+sealed abstract class RPSMove(
+    val icon : String,
+    val value : String) {
+
+    override def toString = icon
+  }
+
+    case object ROCK extends RPSMove("💎", "0")
```
Comment (gabro) [inline src/main/scala/rps/RPSMoves.scala]: The convention is to use PascalCase for identifiers, so this would be `Rock`

File: src/main/scala/rps/RPSMoves.scala [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+    case object PAPER extends RPSMove("📄", "1")
+    case object SCISSORS extends RPSMove("✂️", "2")
+
+    // I need to find a way to obtain this set automagically
+    val setOfMoves: Set[RPSMove] = Set(ROCK, PAPER, SCISSORS)
```
Comment (gabro) [inline src/main/scala/rps/RPSMoves.scala]: FYI, you don't need the `Set[RPSMove]` annotation

File: src/main/scala/rps/RPSMoves.scala [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+The "agile-version" of enumerations are called
+"sealed trait extended by case objects".
+
+Here we define a RPSMoves ADT that will contain
+useful definitions and methods to craft RPS Moves.
+
+*/
+
+
+object RPSMoves {
```
Comment (gabro) [inline src/main/scala/rps/RPSMoves.scala]: The general convention is to define a class as toplevel and then use a [companion object](https://docs.scala-lang.org/tour/singleton-objects.html#companion-objects) for adding static members and namepsacing. In this case, this would look like

```scala
sealed abstract class RPSMove(val icon: String, val value: String)
object RPSMove {
  case object Rock extends RPSMove("💎", "0")
  // ...
}
```

File: src/main/scala/rps/Game.scala [hunk 4]
```diff
@@ -1,30 +1,40 @@
...
+    println(s"Your move was:    ${userMove.get.toString}")
+    println(s"The CPU move was: ${computerMove.get.toString}")
 
     /* Compute the outcome */
-    computeGameOutcome(userMove, computerMove)
+    computeGameOutcome(userMove.get, computerMove.get)
+    }
   }
 
   private def generateCPUMove(): String =
```
Comment (gabro) [inline src/main/scala/rps/Game.scala]: `generateCPUMove` could return directly an `RPSMove`

File: src/main/scala/rps/Game.scala [hunk 5]
```diff
@@ -1,30 +1,40 @@
...
+    |0: ${ROCK.toString}
+    |1: ${PAPER.toString}
+    |2: ${SCISSORS.toString}
     |
     |> """.stripMargin)
 
-    val computerMove = generateCPUMove();
+    val userMove = RPSMoves.factoryMove(userMoveString)
+
+    if (userMove == None) {
```
Comment (gabro) [inline src/main/scala/rps/Game.scala]: When you have an `Option` you generally don't use `if/else` to work with the two possible cases. In this case, I would suggest to use a `match` (which will save you the `.get` below)

File: src/main/scala/rps/RPSMoves.scala [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+
+sealed abstract class RPSMove(
+    val icon : String,
+    val value : String) {
+
+    override def toString = icon
```
Comment (gabro) [inline src/main/scala/rps/RPSMoves.scala]: About attaching "behavioral" data to the class, I suggest you to read my comment to Fede's solution: https://github.com/buildo/rockPaperScissorByFede/pull/9#discussion_r201639206

You can ignore it for now, but it's good to know ;)

**Review by gabro — APPROVED** [review]
👍 nice job! I've left a few comments that should help you align to a more idiomatic use of Scala.

**Review by gabro — CHANGES_REQUESTED** [review]
Woops, approved by mistake

File: src/main/scala/rps/RPSMoves.scala (hunk 1 above)
Comment (raasoft) [reply src/main/scala/rps/RPSMoves.scala]: Gotcha! 🤜🏻

File: src/main/scala/rps/RPSMoves.scala (hunk 2 above)
Comment (raasoft) [reply src/main/scala/rps/RPSMoves.scala]: Thank you! for clarity over brevity (in C this payed off) I usually leave all types declared, but if here in buildo we do otherwise I will change accordingly.

Do you know how to generate that Set automagically out of the enumerator?

Comment (gabro) [reply src/main/scala/rps/RPSMoves.scala]: The general convention is that in obvious cases you leave it out. Reading the code, it's pretty obvious that this is a `Set[RPSMove]`.

In practice, you usually don't include an explicit type annotation when declaring `val`, but it's strongly encourage to always declare the result type of a public method.

> Do you know how to generate that Set automagically out of the enumerator?

Wait for the next steps ;)

File: src/main/scala/rps/RPSMoves.scala (hunk 6 above)
Comment (raasoft) [reply src/main/scala/rps/RPSMoves.scala]: I definitely understood the point about avoiding as much as possible (99% of times) to attach "business logic" to data types, but in this case I just wanted to put in practice an override for the first time (I was curious, and here you go, I got my review!).

[Design issue] The toString function is the one responsible to "render" the object in a textual way. It exists for many objects (e.g. in Java). For each object, exists a default implementation of toString. So the designer of the datatype has to introduce a "bias" about choosing one possible graphical interpretation of the value, and this seems to contradict the fact that abstract data type has to be abstract (no business logic).  To make it more extendible, without knowing well Scala, I would use the "strategy" pattern to change at runtime the way the object is text-rendered. Strategy pattern in functional languages is pretty straightforward too. What about a possible solution here?

File: src/main/scala/rps/RPSMoves.scala (hunk 3 above)
Comment (raasoft) [reply src/main/scala/rps/RPSMoves.scala]: Gotcha! Does this way of writing "agile-enumerators" with a companion object and an abstract class as toplevel has a nickname?

File: src/main/scala/rps/Game.scala (hunk 4 above)
Comment (raasoft) [reply src/main/scala/rps/Game.scala]: For lazyness I didn't change that at all, my bad. :3 

But let's pretend generateCPUMove was public and people was using it (thus I could not change its signature so easily).

Could I change something in such a way generateCPUMove was *simultaneously* returning a string or a RPSMove object? (in this way, the public method would not break the existing calls but would be enhanced anyway with the new support for RPSMove datatype?)

I know this question sounds strange (in C is impossible/not advisable), but maybe some scala features allow this (or even better, it is a well known design pattern).

File: src/main/scala/rps/RPSMoves.scala (hunk 3 above)
Comment (gabro) [reply src/main/scala/rps/RPSMoves.scala]: This is the most common encoding in Scala of a "sum type" (also known in literature as a "coproduct" or "tagged union").

This a specific case of a "sum type" where all members of the type are a single value (i.e. an `object`).

The use of `abstract class` (or `trait`) and the companion object is just practical in Scala, I don't think it has a name.

File: src/main/scala/rps/RPSMoves.scala (hunk 6 above)
Comment (gabro) [reply src/main/scala/rps/RPSMoves.scala]: At a super high-level, you want to have pure data (no behavior attached) and have a separate function for producing a behavior. For example:

```scala
def printMove(move: Move): String = move match {
  case Rock => "rock"
  case Paper => "paper"
  // ...
}
```

As I mentioned in the other comment, this is the foundation of ad-hoc polymorphism, which leads to typeclasses. The answer to your specific question is: use a typeclass. A good candidate for printing is `Show` (which is defined by many FP libraries), but more often you need to transform the value into a JSON string or similar, so you use different typeclasses according to the specific library you're using (we'll see an example in the next steps)

File: src/main/scala/rps/Game.scala (hunk 4 above)
Comment (gabro) [reply src/main/scala/rps/Game.scala]: What you're suggesting is overloading a method by the return type, which is not possible in Scala (and in any other language I'm aware of, FWIW, since it's super hard to typecheck and not so useful).

So, no, you can't (and shouldn't :P )

If you're exposing an API like that, you're pretty much stuck to it.

File: src/main/scala/rps/Game.scala (hunk 5 above)
Comment (raasoft) [reply src/main/scala/rps/Game.scala]: Very useful! Thanks a lot! I was getting horrified at all those .get!

File: src/main/scala/rps/Game.scala (hunk 4 above)
Comment (raasoft) [reply src/main/scala/rps/Game.scala]: I was asking because I wanted to see if in Scala things were different w.r.t. what I already knew. Phew! Nothing new here :D FYI, some languages *may do return type overloading*, like in C#, but since C# adheres to [CLS](https://msdn.microsoft.com/en-us/library/12a7a7h3(v=vs.100).aspx) it is forbidden *by design*.

Comment (gabro) [reply src/main/scala/rps/Game.scala]: Are you sure? I knew the C# spec forbids overloading by return type.

File: src/main/scala/rps/RPSMoves.scala (hunk 6 above)
Comment (raasoft) [reply src/main/scala/rps/RPSMoves.scala]: Gotcha! So the answer is typeclasses :3 Very good!

File: src/main/scala/rps/Game.scala (hunk 4 above)
Comment (raasoft) [reply src/main/scala/rps/Game.scala]: C# specs forbids overloading by return type, is exactly what I said.
What i was stressing out, is that it is like that not because of a [*technical reason*](https://stackoverflow.com/a/20705713), i.e. it was done like that *by design*.

File: src/main/scala/rps/RPSMoves.scala (hunk 3 above)
Comment (raasoft) [reply src/main/scala/rps/RPSMoves.scala]: Perfect! `Sum type`. Better know the nomenclature right from the start!

File: src/main/scala/rps/Game.scala (hunk 4 above)
Comment (gabro) [reply src/main/scala/rps/Game.scala]: Ah yes, it's not technically impossible, it just makes method selection very hard, because you need to consider the context in which the method is called, and not just its invocation.

File: src/main/scala/rps/RPSMoves.scala (hunk 3 above)
Comment (gabro) [reply src/main/scala/rps/RPSMoves.scala]: Another name for this is `Algebraic Data Type`, or `ADT` (not to be confused with `Abstract Data Type`)

File: src/main/scala/rps/RPSMoves.scala [hunk 7]
```diff
@@ -14,22 +14,21 @@ useful definitions and methods to craft RPS Moves.
 
 */
 
-
+sealed abstract class RPSMove(val value : String)
 object RPSMoves {
```
Comment (gabro) [inline src/main/scala/rps/RPSMoves.scala]: in order for this to be a companion object it needs to be called exactly as the class.

Not strictly necessary here, but just FYI

**Review by gabro — APPROVED** [review]
👍

File: src/main/scala/rps/RPSMoves.scala (hunk 7 above)
Comment (raasoft) [reply src/main/scala/rps/RPSMoves.scala]: Gotcha! I'll implement it at the next step ;)
